import type { Agent, Issue } from './types'

export const demoAgents: Agent[] = [
  {
    id: '13eb4ee0',
    name: 'CEO',
    role: 'ceo',
    title: 'Chief Executive Officer',
    icon: null,
    status: 'running',
    urlKey: 'ceo',
    reportsTo: null,
    spentMonthlyCents: 261,
    budgetMonthlyCents: 1500,
    lastHeartbeatAt: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: '4902e9fb',
    name: 'CTO',
    role: 'cto',
    title: 'Chief Technology Officer',
    icon: 'cpu',
    status: 'running',
    urlKey: 'cto',
    reportsTo: '13eb4ee0',
    spentMonthlyCents: 460,
    budgetMonthlyCents: 0,
    lastHeartbeatAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: '972a1f21',
    name: 'CMO',
    role: 'cmo',
    title: 'Chief Marketing Officer',
    icon: 'sparkles',
    status: 'idle',
    urlKey: 'cmo',
    reportsTo: '13eb4ee0',
    spentMonthlyCents: 587,
    budgetMonthlyCents: 0,
    lastHeartbeatAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'bc8e0a9e',
    name: 'Product Manager',
    role: 'pm',
    title: 'Product Manager',
    icon: 'puzzle',
    status: 'idle',
    urlKey: 'product-manager',
    reportsTo: '13eb4ee0',
    spentMonthlyCents: 0,
    budgetMonthlyCents: 0,
    lastHeartbeatAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: '1f039f9d',
    name: 'Lead App Engineer',
    role: 'engineer',
    title: 'Lead Application Engineer',
    icon: 'rocket',
    status: 'running',
    urlKey: 'lead-app-engineer',
    reportsTo: '4902e9fb',
    spentMonthlyCents: 1228,
    budgetMonthlyCents: 5500,
    lastHeartbeatAt: new Date(Date.now() - 1 * 60000).toISOString(),
  },
  {
    id: '120a58ae',
    name: 'Head of Design',
    role: 'designer',
    title: 'Head of Design',
    icon: 'wand',
    status: 'idle',
    urlKey: 'head-of-design',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 401,
    budgetMonthlyCents: 2527,
    lastHeartbeatAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'c67e1549',
    name: 'Mockup Artist',
    role: 'designer',
    title: 'Mockup & Visual Asset Designer',
    icon: 'sparkles',
    status: 'idle',
    urlKey: 'mockup-artist',
    reportsTo: '120a58ae',
    spentMonthlyCents: 82,
    budgetMonthlyCents: 1000,
    lastHeartbeatAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: '56323eaa',
    name: 'Senior Web Engineer',
    role: 'engineer',
    title: 'Senior Full-Stack Engineer (Web)',
    icon: 'code',
    status: 'idle',
    urlKey: 'senior-web-engineer',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 500,
    budgetMonthlyCents: 2538,
    lastHeartbeatAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: '64cc808d',
    name: 'Senior Web Engineer II',
    role: 'engineer',
    title: 'Senior Full-Stack Engineer II',
    icon: 'terminal',
    status: 'idle',
    urlKey: 'senior-web-engineer-ii',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 0,
    budgetMonthlyCents: 2533,
    lastHeartbeatAt: new Date(Date.now() - 5 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: 'aaaf34db',
    name: 'Sr Mobile iOS',
    role: 'engineer',
    title: 'Senior Mobile Engineer (iOS)',
    icon: 'atom',
    status: 'idle',
    urlKey: 'senior-mobile-engineer-ios',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 1464,
    budgetMonthlyCents: 2508,
    lastHeartbeatAt: new Date(Date.now() - 3 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: '1b37aee1',
    name: 'Sr Mobile Android',
    role: 'engineer',
    title: 'Senior Mobile Engineer (Android)',
    icon: 'zap',
    status: 'idle',
    urlKey: 'senior-mobile-engineer-android',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 448,
    budgetMonthlyCents: 2531,
    lastHeartbeatAt: new Date(Date.now() - 3 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: 'a1c5844c',
    name: 'QA Engineer',
    role: 'engineer',
    title: 'QA Engineer',
    icon: 'microscope',
    status: 'idle',
    urlKey: 'qa-engineer',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 28,
    budgetMonthlyCents: 0,
    lastHeartbeatAt: new Date(Date.now() - 4 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: '96041371',
    name: 'Debugger',
    role: 'engineer',
    title: 'Debugger / Bug Fix Engineer',
    icon: 'bug',
    status: 'idle',
    urlKey: 'debugger',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 0,
    budgetMonthlyCents: 0,
    lastHeartbeatAt: new Date(Date.now() - 14 * 24 * 60 * 60000).toISOString(),
  },
  {
    id: 'f7cd2dae',
    name: 'Product Tester',
    role: 'qa',
    title: 'Product Tester (UX)',
    icon: 'eye',
    status: 'idle',
    urlKey: 'product-tester',
    reportsTo: '1f039f9d',
    spentMonthlyCents: 0,
    budgetMonthlyCents: 0,
    lastHeartbeatAt: new Date(Date.now() - 14 * 24 * 60 * 60000).toISOString(),
  },
]

export const demoActiveIssues: Issue[] = [
  {
    id: 'i1',
    identifier: 'APPU-929',
    title: 'Build robust working MINIONS UI',
    status: 'in_progress',
    priority: 'medium',
    assigneeAgentId: '1f039f9d',
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    projectId: '998d5ae9',
  },
  {
    id: 'i2',
    identifier: 'APPU-924',
    title: 'Scaffold LinguaFlash app with demo mode',
    status: 'in_progress',
    priority: 'high',
    assigneeAgentId: '56323eaa',
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'i3',
    identifier: 'APPU-920',
    title: 'Daily app concept: fitness challenge tracker',
    status: 'in_progress',
    priority: 'medium',
    assigneeAgentId: '972a1f21',
    updatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'i4',
    identifier: 'APPU-911',
    title: 'Review Firebase security rules',
    status: 'todo',
    priority: 'high',
    assigneeAgentId: '4902e9fb',
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'i5',
    identifier: 'APPU-918',
    title: 'Design app onboarding flow wireframes',
    status: 'todo',
    priority: 'medium',
    assigneeAgentId: '120a58ae',
    updatedAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'i6',
    identifier: 'APPU-915',
    title: 'Fix memory leak in real-time listener',
    status: 'blocked',
    priority: 'critical',
    assigneeAgentId: '96041371',
    updatedAt: new Date(Date.now() - 3 * 60 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'i7',
    identifier: 'APPU-916',
    title: 'Implement push notifications for iOS',
    status: 'in_progress',
    priority: 'high',
    assigneeAgentId: 'aaaf34db',
    updatedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'i8',
    identifier: 'APPU-917',
    title: 'Android deep linking configuration',
    status: 'todo',
    priority: 'medium',
    assigneeAgentId: '1b37aee1',
    updatedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    projectId: null,
  },
]

export const demoDoneIssues: Issue[] = [
  {
    id: 'd1',
    identifier: 'APPU-928',
    title: 'Transcribe and analyze competitor AI agent video',
    status: 'done',
    priority: 'critical',
    assigneeAgentId: '1f039f9d',
    updatedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    projectId: '998d5ae9',
  },
  {
    id: 'd2',
    identifier: 'APPU-910',
    title: 'Deploy LinguaFlash to Vercel with demo mode',
    status: 'done',
    priority: 'high',
    assigneeAgentId: '56323eaa',
    updatedAt: new Date(Date.now() - 2 * 60 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'd3',
    identifier: 'APPU-907',
    title: 'Set up Firebase auth for mood tracker',
    status: 'done',
    priority: 'medium',
    assigneeAgentId: '64cc808d',
    updatedAt: new Date(Date.now() - 5 * 60 * 60000).toISOString(),
    projectId: null,
  },
  {
    id: 'd4',
    identifier: 'APPU-902',
    title: 'iOS TestFlight build submission',
    status: 'done',
    priority: 'high',
    assigneeAgentId: 'aaaf34db',
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60000).toISOString(),
    projectId: null,
  },
]
