import type { RoomConfig } from './types'

export const ROOMS: RoomConfig[] = [
  {
    id: 'bridge',
    name: 'THE BRIDGE',
    emoji: '⚡',
    description: 'Command & Control — where strategy is set',
    agentUrlKeys: ['ceo', 'cto'],
    color: '#c800ff',
    gridArea: 'bridge',
  },
  {
    id: 'strategy',
    name: 'STRATEGY',
    emoji: '📡',
    description: 'CMO + PM — product vision & market intel',
    agentUrlKeys: ['cmo', 'product-manager'],
    color: '#ffb700',
    gridArea: 'strategy',
  },
  {
    id: 'factory',
    name: 'FACTORY',
    emoji: '⚙️',
    description: 'Web engineering — features ship here',
    agentUrlKeys: ['lead-app-engineer', 'senior-web-engineer', 'senior-web-engineer-ii'],
    color: '#00ff41',
    gridArea: 'factory',
  },
  {
    id: 'mobile',
    name: 'MOBILE LAB',
    emoji: '📱',
    description: 'iOS + Android — Squad Beta',
    agentUrlKeys: ['senior-mobile-engineer-ios', 'senior-mobile-engineer-android'],
    color: '#00d4ff',
    gridArea: 'mobile',
  },
  {
    id: 'design',
    name: 'DESIGN STUDIO',
    emoji: '🎨',
    description: 'UX flows, mockups & visual assets',
    agentUrlKeys: ['head-of-design', 'mockup-artist'],
    color: '#ff6ad5',
    gridArea: 'design',
  },
  {
    id: 'warroom',
    name: 'WAR ROOM',
    emoji: '🔥',
    description: 'QA, Debugger, Tester — nothing ships broken',
    agentUrlKeys: ['qa-engineer', 'debugger', 'product-tester'],
    color: '#ff3131',
    gridArea: 'warroom',
  },
  {
    id: 'treasury',
    name: 'TREASURY',
    emoji: '💰',
    description: 'Budget tracking — cost per agent',
    agentUrlKeys: [],
    color: '#ffd700',
    gridArea: 'treasury',
  },
  {
    id: 'archives',
    name: 'ARCHIVES',
    emoji: '🗄️',
    description: 'Completed missions — the memory vault',
    agentUrlKeys: [],
    color: '#7a8a7a',
    gridArea: 'archives',
  },
  {
    id: 'quarters',
    name: 'QUARTERS',
    emoji: '🎮',
    description: 'Idle agents — keeping morale up',
    agentUrlKeys: [],
    color: '#4a6a4a',
    gridArea: 'quarters',
  },
]
