import type { RoomConfig } from './types'

export const ROOMS: RoomConfig[] = [
  {
    id: 'bridge',
    name: 'THE BRIDGE',
    emoji: '⚡',
    description: 'Command & Control — Ultron reigns here',
    agentIds: ['13eb4ee0', '4902e9fb'],
    color: '#c800ff',
    gridArea: 'bridge',
  },
  {
    id: 'strategy',
    name: 'STRATEGY',
    emoji: '📡',
    description: 'CMO + PM — product vision & market intel',
    agentIds: ['972a1f21', 'bc8e0a9e'],
    color: '#ffb700',
    gridArea: 'strategy',
  },
  {
    id: 'factory',
    name: 'FACTORY',
    emoji: '⚙️',
    description: 'Web engineering — features ship here',
    agentIds: ['1f039f9d', '56323eaa', '64cc808d'],
    color: '#00ff41',
    gridArea: 'factory',
  },
  {
    id: 'mobile',
    name: 'MOBILE LAB',
    emoji: '📱',
    description: 'iOS + Android — Squad Beta',
    agentIds: ['aaaf34db', '1b37aee1'],
    color: '#00d4ff',
    gridArea: 'mobile',
  },
  {
    id: 'design',
    name: 'DESIGN STUDIO',
    emoji: '🎨',
    description: 'UX flows, mockups & visual assets',
    agentIds: ['120a58ae', 'c67e1549'],
    color: '#ff6ad5',
    gridArea: 'design',
  },
  {
    id: 'warroom',
    name: 'WAR ROOM',
    emoji: '🔥',
    description: 'QA, Debugger, Tester — nothing ships broken',
    agentIds: ['a1c5844c', '96041371', 'f7cd2dae'],
    color: '#ff3131',
    gridArea: 'warroom',
  },
  {
    id: 'treasury',
    name: 'TREASURY',
    emoji: '💰',
    description: 'Budget tracking — cost per agent',
    agentIds: [],
    color: '#ffd700',
    gridArea: 'treasury',
  },
  {
    id: 'archives',
    name: 'ARCHIVES',
    emoji: '🗄️',
    description: 'Completed missions — the memory vault',
    agentIds: [],
    color: '#7a8a7a',
    gridArea: 'archives',
  },
  {
    id: 'quarters',
    name: 'QUARTERS',
    emoji: '🎮',
    description: 'Idle agents — keeping morale up',
    agentIds: [],
    color: '#4a6a4a',
    gridArea: 'quarters',
  },
]
